font_family JetBrainsMono Nerd Font
font_size 12

disable_ligatures always

#cursor_trail 5
#cursor_trail_decay 0.1 0.4

window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor
enable_audio_bell no

background_opacity 0.75
