source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 350, 70
    position = 0, -80

    halign = center
    valign = center

    inner_color = rgba(7,17,31,0.85)
    outer_color = rgba(34,211,238,0.9)
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = rgba(219,234,254,1)

    placeholder_text = Password...
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 16
    shadow_passes = 3
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}

image {
    monitor =
    path = ~/.config/hyprlock/wallhaven-95kx6d_3840x2160.png

    size = 500
    rounding = -1

    border_size = 3
    border_color = rgba(34,211,238,1)

    position = 0, 100
    halign = center
    valign = center
}
