--return {
--  {
--    "blazkowolf/gruber-darker.nvim",
--    priority = 1000,
--    lazy = false,
--    config = function()
--      vim.api.nvim_create_autocmd("ColorScheme", {
--        pattern = "gruber-darker",
--        callback = function()
--          vim.api.nvim_set_hl(0, "@property", {
--            fg = "#ffffff",
--          })
--
--         vim.api.nvim_set_hl(0, "@lsp.type.property", {
--            fg = "#ffffff",
--          })
--        end,
--      })

--      vim.cmd.colorscheme("gruber-darker")
--   end,
--  },
--}
return {}
